services:
  - type: web
    name: quickbite-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://Dev_Rolaj:Rolaj_Ijinle93@cluster0.bvv6aat.mongodb.net/QuickBiteDB?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_NAME
        value: dtkyv2d3x
      - key: CLOUDINARY_API_KEY
        value: 294698414177843
      - key: CLOUDINARY_API_SECRET
        value: GPG36T2mpLtS9xe_MYx1s_h16hU

  - type: static
    name: quickbite-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://quickbite-backend-bqzt.onrender.com/api

databases:
  - name: quickbite-db
    databaseName: quickbitedb
    plan: free
